apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    env: prod
    app: main
    tier: frontend
    owner: KirillOstapchuk
spec:
  containers:
    - name: apache
      image: httpd:latest
      ports:
        - containerPort: 80
    - name: tomcat
      image: tomcat:8.5.38
      ports:
        - containerPort: 8080
